# Generated by Django 4.2.1 on 2023-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_is_active_client_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CallUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
            ],
        ),
    ]
