# Generated by Django 4.2.1 on 2023-06-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_callchauffeur_calluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallChauffeur',
        ),
        migrations.DeleteModel(
            name='CallUser',
        ),
    ]
