# Generated by Django 4.0.6 on 2023-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_callchauffeur_delete_calluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='subscribePath',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
