# Generated by Django 4.2.1 on 2023-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_imagepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imagePayment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
