# Generated by Django 4.2.1 on 2023-06-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_imagepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='imagePayment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitudeDestination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitudeDriver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitudeDestination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitudeDriver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitudeMyLocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ratingDriver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='typeCar',
        ),
    ]
