# Generated by Django 4.2.1 on 2023-06-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_imagepayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='idDriver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitudeMyLocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modelCar',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nameCustomer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nameDestinations',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nameDriver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nameLocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numberOfPassengers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numberingPlate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phoneCustomer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phoneDriver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profileCustomer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profileDriver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicleImage',
        ),
    ]
