# Generated by Django 4.0.6 on 2023-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_iddriver_order_imagepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='latitudeDriver',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='longitudeDriver',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rating',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitudeDestination',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitudeDriver',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitudeMyLocation',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitudeDestination',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitudeDriver',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitudeMyLocation',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ratingDriver',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
    ]
