# Generated by Django 4.0.6 on 2023-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_offer_latitudedriver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='latitudeDriver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='longitudeDriver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='minutes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rating',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='typeCar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitudeDestination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitudeDriver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitudeMyLocation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitudeDestination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitudeDriver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitudeMyLocation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='minutes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='ratingDriver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='typeCar',
            field=models.CharField(max_length=255),
        ),
    ]
